# Generated by Django 2.1.5 on 2023-03-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20230222_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('stars', models.IntegerField(default=0)),
                ('reviews', models.CharField(max_length=128)),
            ],
        ),
    ]
