# Generated by Django 2.1.5 on 2023-03-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
